CarRentalServies/Areas/Admin/Controllers/AddressBookController.cs
using CarRentalServies.Areas.Admin.DAL;
using CarRentalServies.Areas.Admin.Models;
using CarRentalServies.BAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace CarRentalServies.Areas.Admin.Controllers
{
    [CheckAccess]
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    public class AddressBookController : Controller
    {
        AddressBook_DAL addDal = new AddressBook_DAL();
        public IActionResult Index()
        {
            return View();
        }
        
        #region CountryList
        public IActionResult CountryList()
        {
            DataTable dataTable = addDal.CountrySelecttAll();
            return View(dataTable);
        }
        #endregion

        #region Country Delete
        public IActionResult CountryDelete(int CountryID)
        {
            bool isSuccess = addDal.CountryDelete(CountryID);

            if (isSuccess)
            {
                return RedirectToAction("CountryList");
            }
            return RedirectToAction("CountryList");
        }
        #endregion

        #region CountrySave
        public IActionResult CountrySave(CountryModel modelCountry)
        {
            if (ModelState.IsValid)
            {
                if (addDal.CountrySave(modelCountry))
                {
                    return RedirectToAction("CountryList");
                }

            }
            return View("CountryAddEdit");
        }
        #endregion

        #region CountryAddEdit
        public IActionResult CountryAddEdit(int CountryID)
        {
            CountryModel modelCountry = addDal.CountryByID(CountryID);

            if (modelCountry != null)
            {
                TempData["PageTitle"] = "Country Edit Page";
                return View("CountryAddEdit", modelCountry);
            }
            else
            {
                TempData["PageTitle"] = "Country Add Page";
                return View("CountryAddEdit");
            }
        }
        #endregion

        #region StateList
        public IActionResult StateList()
        {
            DataTable dataTable = addDal.StateSelecttAll();
            ViewBag.CountryList = addDal.CountryDropDown();
            return View(dataTable);
        }
        #endregion

        #region State Delete
        public IActionResult StateDelete(int StateID)
        {
            bool isSuccess = addDal.StateDelete(StateID);

            if (isSuccess)
            {
                return RedirectToAction("StateList");
            }
            return RedirectToAction("StateList");
        }
        #endregion

        #region StateSave
        public IActionResult StateSave(StateModel modelState)
        {
            if (ModelState.IsValid)
            {
                if (addDal.StateSave(modelState))
                {
                    return RedirectToAction("StateList");
                }

            }
            return View("StateAddEdit");
        }
        #endregion

        #region StateAddEdit
        public IActionResult StateAddEdit(int StateID)
        {
            StateModel modelState = addDal.StateByID(StateID);

            if (modelState != null)
            {
                TempData["PageTitle"] = "Country Edit Page";
                ViewBag.CountryList = addDal.CountryDropDown();
                return View("StateAddEdit", modelState);
            }
            else
            {
                TempData["PageTitle"] = "Country Add Page";
                ViewBag.CountryList = addDal.CountryDropDown();
                return View("StateAddEdit");
            }
        }
        #endregion

        #region CityList
        public IActionResult CityList()
        {
            DataTable dataTable = addDal.CitySelecttAll();
            ViewBag.StateList = addDal.StateDropDown();
            ViewBag.CountryList = addDal.CountryDropDown();
            return View(dataTable);
        }
        #endregion

        #region City Delete
        public IActionResult CityDelete(int CityID)
        {
            bool isSuccess = addDal.CityDelete(CityID);

            if (isSuccess)
            {
                return RedirectToAction("CityList");
            }
            return RedirectToAction("CityList");
        }
        #endregion

        #region CitySave
        public IActionResult CitySave(CityModel modelCity)
        {
            if (ModelState.IsValid)
            {
                if (addDal.CitySave(modelCity))
                {
                    return RedirectToAction("CityList");
                }

            }
            return View("CityAddEdit");
        }
        #endregion

        #region CityAddEdit
        public IActionResult CityAddEdit(int CityID)
        {
            CityModel modelCity = addDal.CityByID(CityID);

            if (modelCity != null)
            {
                TempData["PageTitle"] = "Country Edit Page";
                ViewBag.StateList = addDal.StateDropDown();
                return View("CityAddEdit", modelCity);
            }
            else
            {
                TempData["PageTitle"] = "Country Add Page";
                ViewBag.StateList = addDal.StateDropDown();
                return View("CityAddEdit");
            }
        }
        #endregion

        #region Country Filter
        public IActionResult CountryFilter(CountryFilterModel filterModel)
        {
            DataTable dataTable = addDal.CountryFilter(filterModel);
            return View("CountryList",dataTable);
        }
        #endregion

        #region State Filter
        public IActionResult StateFilter(StateFilterModel filterModel)
        {
            DataTable dataTable = addDal.StateFilter(filterModel);
            ViewBag.CountryList = addDal.CountryDropDown();
            return View("StateList", dataTable);
        }
        #endregion

        #region City Filter
        public IActionResult CityFilter(CityFilterModel filterModel)
        {
            DataTable dataTable = addDal.CityFilter(filterModel);
            ViewBag.StateList = addDal.StateDropDown();
            ViewBag.CountryList = addDal.CountryDropDown();
            return View("CityList", dataTable);
        }
        #endregion
    }
}

CarRentalServies/Areas/Admin/Views/AddressBook/CityAddEdit.cshtml
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
}
@model CarRentalServies.Areas.Admin.Models.CityModel

<div class="pagetitle">
    <h1>State Add/Edit Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item">City</li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="card">
    <div class="card-body">
        <h5 class="card-title">City Add/Edit Page</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="CitySave" asp-area="Admin">
            @Html.HiddenFor(x => x.CityID)

            <div class="col-md-12">
                <input type="text" class="form-control" placeholder="CityName" asp-for="CityName">
            </div>
            <div class="col-md-6">
                <input type="text" class="form-control" placeholder="CityCode" asp-for="CityCode">
            </div>
            <div class="col-md-6">
                <select class="form-select" asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))">
                    <option>Select State</option>
                </select>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

CarRentalServies/Areas/Admin/Views/AddressBook/CityList.cshtml
@using CarRentalServies.Areas.Admin.Models
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
    CityFilterModel filterModel = new CityFilterModel();
}
@using System.Data
@model DataTable

<div class="pagetitle">
    <h1>City List Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">City List</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Filter</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="CityFilter" asp-area="Admin">
            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="StateName" asp-for="@filterModel.CityName">
            </div>
            <div class="col-md-4">
                <select class="form-select" asp-for="@filterModel.StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))">
                    <option>Select Country</option>
                </select>
            </div>
            <div class="col-md-4">
                <select class="form-select" asp-for="@filterModel.CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))">
                    <option>Select Country</option>
                </select>
            </div>

            <div class="col-md-4">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="d-flex justify-content-between card-header">
                    <div class="">
                        <h5>City List</h5>
                    </div>
                    <div class="">
                        <a asp-area="Admin" asp-controller="AddressBook" asp-action="CityAddEdit">
                            <input type="button" class="btn btn-success" value="Add City" />
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <br />

                    <!-- Table with hoverable rows -->
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">City Name</th>
                                <th scope="col">City Code</th>
                                <th scope="col">State Name</th>
                                <th scope="col">Country Name</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@dr["CityName"]</td>
                                    <td>@dr["CityCode"]</td>
                                    <td>@dr["StateName"]</td>
                                    <td>@dr["CountryName"]</td>
                                    <td>
                                        <div class="d-flex">

                                            <div class="me-2">
                                                <form method="post" asp-area="Admin" asp-controller="Addressbook" asp-action="CityDelete">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["CityID"])" name="CityID" />
                                                    <button type="submit" class="btn btn-danger" value="Delete" onclick="return fun1();">Delete</button>
                                                </form>
                                            </div>
                                            <div class="ms-2">
                                                <form asp-area="Admin" asp-controller="Addressbook" asp-action="CityAddEdit">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["CityID"])" name="CityID" />
                                                    <button type="submit" class="btn btn-info" value="Edit">Edit</button>
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- End Table with hoverable rows -->

                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts
    {
    <script>
        function fun1() {
            if (confirm("Are you sure you want to delete?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}

CarRentalServies/Areas/Admin/Views/AddressBook/CountryAddEdit.cshtml
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
}
@model CarRentalServies.Areas.Admin.Models.CountryModel

<div class="pagetitle">
    <h1>Car Add/Edit Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item">Users</li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Car Add/Edit Page</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="CountrySave" asp-area="Admin">
            @Html.HiddenFor(x => x.CountryID)

            <div class="col-md-12">
                <input type="text" class="form-control" placeholder="Country Name" asp-for="CountryName">
            </div>
            <div class="col-md-6">
                <input type="text" class="form-control" placeholder="Country Code" asp-for="CountryCode">
            </div>
            

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

CarRentalServies/Areas/Admin/Views/AddressBook/CountryList.cshtml
@using CarRentalServies.Areas.Admin.Models
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
    CountryFilterModel filterModel = new CountryFilterModel();
}
@using System.Data
@model DataTable

<div class="pagetitle">
    <h1>Country List Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Country List</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Filter</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="CountryFilter" asp-area="Admin">
            

            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="CountryName" asp-for="@filterModel.CountryName">
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="CountryCode" asp-for="@filterModel.CountryCode">
            </div>

            <div class="col-md-4">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="d-flex justify-content-between card-header">
                    <div class="">
                        <h5>Country List</h5>
                    </div>
                    <div class="">
                        <a asp-area="Admin" asp-controller="AddressBook" asp-action="CountryAddEdit">
                            <input type="button" class="btn btn-success" value="Add Country" />
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <br />

                    <!-- Table with hoverable rows -->
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Country Name</th>
                                <th scope="col">Country Code</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@dr["CountryName"]</td>
                                    <td>@dr["CountryCode"]</td>
                                    <td>
                                        <div class="d-flex">

                                            <div class="me-2">
                                                <form method="post" asp-area="Admin" asp-controller="Addressbook" asp-action="CountryDelete">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["CountryID"])" name="CountryID" />
                                                    <button type="submit" class="btn btn-danger" value="Delete" onclick="return fun1();">Delete</button>
                                                </form>
                                            </div>
                                            <div class="ms-2">
                                                <form asp-area="Admin" asp-controller="Addressbook" asp-action="CountryAddEdit">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["CountryID"])" name="CountryID" />
                                                    <button type="submit" class="btn btn-info" value="Edit">Edit</button>
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- End Table with hoverable rows -->

                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts
    {
    <script>
        function fun1() {
            if (confirm("Are you sure you want to delete?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}

CarRentalServies/Areas/Admin/Views/AddressBook/StateAddEdit.cshtml
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
}
@model CarRentalServies.Areas.Admin.Models.StateModel

<div class="pagetitle">
    <h1>State Add/Edit Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item">State</li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="card">
    <div class="card-body">
        <h5 class="card-title">State Add/Edit Page</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="StateSave" asp-area="Admin">
            @Html.HiddenFor(x => x.StateID)

            <div class="col-md-12">
                <input type="text" class="form-control" placeholder="StateNameName" asp-for="StateName">
            </div>
            <div class="col-md-6">
                <input type="text" class="form-control" placeholder="StateCode" asp-for="StateCode">
            </div>
            <div class="col-md-6">
                <select class="form-select" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))">
                    <option>Select Country</option>
                </select>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

CarRentalServies/Areas/Admin/Views/AddressBook/StateList.cshtml
@using CarRentalServies.Areas.Admin.Models
@{
    Layout = "~/Areas/Admin/Views/shared/_Admin_Layout.cshtml";
    StateFilterModel filterModel = new StateFilterModel();
}
@using System.Data
@model DataTable

<div class="pagetitle">
    <h1>State List Page</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">State List</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Filter</h5>

        <!-- No Labels Form -->
        <form class="row g-3" method="post" asp-controller="AddressBook" asp-action="StateFilter" asp-area="Admin">
            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="StateName" asp-for="@filterModel.StateName">
            </div>
            <div class="col-md-4">
                <select class="form-select" asp-for="@filterModel.CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))">
                    <option>Select Country</option>
                </select>
            </div>

            <div class="col-md-4">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form><!-- End No Labels Form -->

    </div>

</div>

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="d-flex justify-content-between card-header">
                    <div class="">
                        <h5>State List</h5>
                    </div>
                    <div class="">
                        <a asp-area="Admin" asp-controller="AddressBook" asp-action="StateAddEdit">
                            <input type="button" class="btn btn-success" value="Add State" />
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <br />

                    <!-- Table with hoverable rows -->
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">State Name</th>
                                <th scope="col">State Code</th>
                                <th scope="col">Country Name</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@dr["StateName"]</td>
                                    <td>@dr["StateCode"]</td>
                                    <td>@dr["CountryName"]</td>
                                    <td>
                                        <div class="d-flex">

                                            <div class="me-2">
                                                <form method="post" asp-area="Admin" asp-controller="Addressbook" asp-action="StateDelete">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["StateID"])" name="StateID" />
                                                    <button type="submit" class="btn btn-danger" value="Delete" onclick="return fun1();">Delete</button>
                                                </form>
                                            </div>
                                            <div class="ms-2">
                                                <form asp-area="Admin" asp-controller="Addressbook" asp-action="StateAddEdit">
                                                    <input type="hidden" value="@Convert.ToInt32(dr["StateID"])" name="StateID" />
                                                    <button type="submit" class="btn btn-info" value="Edit">Edit</button>
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- End Table with hoverable rows -->

                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts
    {
    <script>
        function fun1() {
            if (confirm("Are you sure you want to delete?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}